#!/bin/bash
if [ ! -d fastai ]; then
        echo "Installing [torch]"
        pip install pillow==4.2.1 --upgrade
        #pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cu92/torch_nightly.html --upgrade
        #pip install torch<0.4
        #pip install torchtext==0.2.3
        #pip install torchvision==0.2.0
        #pip install pandas==0.20.3

        sed -n -e '/^tmpfs \/dev\/shm tmpfs defaults,size=/!p' -e '$atmpfs \/dev\/shm tmpfs defaults,size=1g 0 0' -i /etc/fstab
        mount -o remount /dev/shm

        mkdir -p /root/.torch/models
        mkdir -p /root/.fastai/data
        ln -s /root/.torch/models /content
        ln -s /root/.fastai/data /content
        rm -rf /content/sample_data/
        
        #git clone https://github.com/fastai/course-v3
        git clone https://github.com/fastai/fastai.git   
        
        cd fastai
        git checkout tags/0.7.0
        pip install fastai==0.7.0
        pip install -r requirements.txt
fi

#pip install dataclasses


